### ISSUE TITLE
json_pure and continuent-monitors-nagios require ruby 1.9

### ISSUE THREAD

**Issue by thekoma** [continuent/continuent-vagrant#32]
Looks like some gem installation fails because of ruby Version:

```
==> db2: Error: Could not update: Execution of '/usr/bin/gem install --no-rdoc --no-ri continuent-monitors-nagios' returned 1: ERROR:  Error installing continuent-monitors-nagios:


==> db2: Error: Execution of '/usr/bin/gem install --no-rdoc --no-ri json_pure' returned 1: ERROR:  Error installing json_pure:

```
Those packages require ruby 1.9 so you should either define a working version with 1.8 or bundle it in other way.

**Comment by mccont** [comment]
Ruby 1.8 is no longer a support version of Ruby - it went out of support in 2012 and out of security support in 1.9. There are no plans at this time to continue to support such an old version of Ruby. 

Currently we target all products to require at least 1.9 and prefer 2.2 or higher.
